apiVersion: v1alpha
kind: espresso
sauce:
  region: us-west-1
  concurrency: 2
  retries: 1
    
  metadata:
    tags:
      - mux-player
      - android
      - data
    # best overridden from the CLI using --build
    build: "Mux Data for Media3"
espresso:
  app: automatedtests/build/outputs/apk/At_latest/debug/automatedtests-At_latest-debug.apk
  testApp: automatedtests/build/outputs/apk/androidTest/At_latest/debug/automatedtests-At_latest-debug-androidTest.apk
suites:
  - name: 'Mux Data Media3 :automatedtests Any Pixel'
    devices:
      - name: Google Pixel.*

